### ISSUE TITLE
allow python-tested-version to be exactly one

### ISSUE THREAD

**Issue by giocaizzi** [giocaizzi/python-dev-actions#21]
python-tested-version for the case only one version.

better way than passing the list

```yaml
  deploy-setuptools:
    uses: giocaizzi/python-dev-actions/.github/workflows/deployment.yml@main
    secrets: inherit
    with:
      python-version: "3.7"
      python-tested-versions: "['3.7']"
      python-build-backend: "setuptools"

```
